Release v0.3.0
fluxcd/image-automation-controller pull request #88
Opened 2021-01-14 18:21 UTC by hiddeco

2021-01-14 18:24 UTC, squaremo requested changes

2021-01-14 18:24 UTC, squaremo commented on CHANGELOG.md
> +making it possible to push changes to Git server that require
```suggestion
making it possible to push changes to Git servers that require
```

2021-01-14 18:24 UTC, squaremo commented on CHANGELOG.md
> +* Upgrade controller-runtime to v0.0.7
```suggestion
* Upgrade controller-runtime to v0.7.0
```

2021-01-15 09:15 UTC, stefanprodan approved these changes
LGTM

2021-01-15 09:21 UTC, merged